//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoredProcedureName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedureName() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.Resources.StoredProcedureName", typeof(StoredProcedureName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_AppSettings_SelectCommand].
        /// </summary>
        internal static string spr_AppSettings_SelectCommand {
            get {
                return ResourceManager.GetString("spr_AppSettings_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Companies_InsertCommand].
        /// </summary>
        internal static string spr_Companies_InsertCommand {
            get {
                return ResourceManager.GetString("spr_Companies_InsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Companies_SelectCommand].
        /// </summary>
        internal static string spr_Companies_SelectCommand {
            get {
                return ResourceManager.GetString("spr_Companies_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Companies_UpdateCommand].
        /// </summary>
        internal static string spr_Companies_UpdateCommand {
            get {
                return ResourceManager.GetString("spr_Companies_UpdateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Options_DeleteCommand].
        /// </summary>
        internal static string spr_Options_DeleteCommand {
            get {
                return ResourceManager.GetString("spr_Options_DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Options_InsertCommand].
        /// </summary>
        internal static string spr_Options_InsertCommand {
            get {
                return ResourceManager.GetString("spr_Options_InsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Options_SelectCommand].
        /// </summary>
        internal static string spr_Options_SelectCommand {
            get {
                return ResourceManager.GetString("spr_Options_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Options_UpdateCommand].
        /// </summary>
        internal static string spr_Options_UpdateCommand {
            get {
                return ResourceManager.GetString("spr_Options_UpdateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_OptionsByProfile_DeleteCommand].
        /// </summary>
        internal static string spr_OptionsByProfile_DeleteCommand {
            get {
                return ResourceManager.GetString("spr_OptionsByProfile_DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_OptionsByProfile_InsertCommand].
        /// </summary>
        internal static string spr_OptionsByProfile_InsertCommand {
            get {
                return ResourceManager.GetString("spr_OptionsByProfile_InsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_OptionsByProfile_SelectCommand].
        /// </summary>
        internal static string spr_OptionsByProfile_SelectCommand {
            get {
                return ResourceManager.GetString("spr_OptionsByProfile_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].spr_Permissions_DeleteCommand.
        /// </summary>
        internal static string spr_Permissions_DeleteCommand {
            get {
                return ResourceManager.GetString("spr_Permissions_DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Permissions_InsertCommand].
        /// </summary>
        internal static string spr_Permissions_InsertCommand {
            get {
                return ResourceManager.GetString("spr_Permissions_InsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Permissions_SelectCommand].
        /// </summary>
        internal static string spr_Permissions_SelectCommand {
            get {
                return ResourceManager.GetString("spr_Permissions_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Permissions_UpdateCommand].
        /// </summary>
        internal static string spr_Permissions_UpdateCommand {
            get {
                return ResourceManager.GetString("spr_Permissions_UpdateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].spr_PermissionsByOptions_DeleteCommand.
        /// </summary>
        internal static string spr_PermissionsByOptions_DeleteCommand {
            get {
                return ResourceManager.GetString("spr_PermissionsByOptions_DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_PermissionsByOptions_InsertCommand].
        /// </summary>
        internal static string spr_PermissionsByOptions_InsertCommand {
            get {
                return ResourceManager.GetString("spr_PermissionsByOptions_InsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_PermissionsByOptions_SelectCommand].
        /// </summary>
        internal static string spr_PermissionsByOptions_SelectCommand {
            get {
                return ResourceManager.GetString("spr_PermissionsByOptions_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_PermissionsOptionsByProfile_DeleteCommand].
        /// </summary>
        internal static string spr_PermissionsOptionsByProfile_DeleteCommand {
            get {
                return ResourceManager.GetString("spr_PermissionsOptionsByProfile_DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_PermissionsOptionsByProfile_InsertCommand].
        /// </summary>
        internal static string spr_PermissionsOptionsByProfile_InsertCommand {
            get {
                return ResourceManager.GetString("spr_PermissionsOptionsByProfile_InsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_PermissionsOptionsByProfile_SelectCommand].
        /// </summary>
        internal static string spr_PermissionsOptionsByProfile_SelectCommand {
            get {
                return ResourceManager.GetString("spr_PermissionsOptionsByProfile_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].spr_Profiles_DeleteCommand.
        /// </summary>
        internal static string spr_Profiles_DeleteCommand {
            get {
                return ResourceManager.GetString("spr_Profiles_DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Profiles_InsertCommand].
        /// </summary>
        internal static string spr_Profiles_InsertCommand {
            get {
                return ResourceManager.GetString("spr_Profiles_InsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Profiles_SelectCommand].
        /// </summary>
        internal static string spr_Profiles_SelectCommand {
            get {
                return ResourceManager.GetString("spr_Profiles_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Profiles_UpdateCommand].
        /// </summary>
        internal static string spr_Profiles_UpdateCommand {
            get {
                return ResourceManager.GetString("spr_Profiles_UpdateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Users_DeleteCommand].
        /// </summary>
        internal static string spr_Users_DeleteCommand {
            get {
                return ResourceManager.GetString("spr_Users_DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Users_InsertCommand].
        /// </summary>
        internal static string spr_Users_InsertCommand {
            get {
                return ResourceManager.GetString("spr_Users_InsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Users_SelectCommand].
        /// </summary>
        internal static string spr_Users_SelectCommand {
            get {
                return ResourceManager.GetString("spr_Users_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Users_UpdateCommand].
        /// </summary>
        internal static string spr_Users_UpdateCommand {
            get {
                return ResourceManager.GetString("spr_Users_UpdateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_Users_ValidateRecoverPasswordCommand].
        /// </summary>
        internal static string spr_Users_ValidateRecoverPasswordCommand {
            get {
                return ResourceManager.GetString("spr_Users_ValidateRecoverPasswordCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].spr_UsersTypes_DeleteCommand.
        /// </summary>
        internal static string spr_UsersTypes_DeleteCommand {
            get {
                return ResourceManager.GetString("spr_UsersTypes_DeleteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_UsersTypes_InsertCommand].
        /// </summary>
        internal static string spr_UsersTypes_InsertCommand {
            get {
                return ResourceManager.GetString("spr_UsersTypes_InsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_UsersTypes_SelectCommand].
        /// </summary>
        internal static string spr_UsersTypes_SelectCommand {
            get {
                return ResourceManager.GetString("spr_UsersTypes_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].[spr_UsersTypes_UpdateCommand].
        /// </summary>
        internal static string spr_UsersTypes_UpdateCommand {
            get {
                return ResourceManager.GetString("spr_UsersTypes_UpdateCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].spr_UserTypes_InsertCommand.
        /// </summary>
        internal static string spr_UserTypes_InsertCommand {
            get {
                return ResourceManager.GetString("spr_UserTypes_InsertCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].spr_UserTypes_SelectCommand.
        /// </summary>
        internal static string spr_UserTypes_SelectCommand {
            get {
                return ResourceManager.GetString("spr_UserTypes_SelectCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a [dbo].spr_UserTypes_UpdateCommand.
        /// </summary>
        internal static string spr_UserTypes_UpdateCommand {
            get {
                return ResourceManager.GetString("spr_UserTypes_UpdateCommand", resourceCulture);
            }
        }
    }
}
