//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StoredProcedureParameterName {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StoredProcedureParameterName() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataAccess.Resources.StoredProcedureParameterName", typeof(StoredProcedureParameterName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ChangePassword.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @CodeInterface.
        /// </summary>
        internal static string CodeInterface {
            get {
                return ResourceManager.GetString("CodeInterface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @CompanyId.
        /// </summary>
        internal static string CompanyId {
            get {
                return ResourceManager.GetString("CompanyId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @CreationDate.
        /// </summary>
        internal static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @DatabaseName.
        /// </summary>
        internal static string DatabaseName {
            get {
                return ResourceManager.GetString("DatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @DateExpiryAccount.
        /// </summary>
        internal static string DateExpiryAccount {
            get {
                return ResourceManager.GetString("DateExpiryAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @DateLastChangePassword.
        /// </summary>
        internal static string DateLastChangePassword {
            get {
                return ResourceManager.GetString("DateLastChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @DaysChangePassword.
        /// </summary>
        internal static string DaysChangePassword {
            get {
                return ResourceManager.GetString("DaysChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @FailedPasswordCount.
        /// </summary>
        internal static string FailedPasswordCount {
            get {
                return ResourceManager.GetString("FailedPasswordCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @FirstLastName.
        /// </summary>
        internal static string FirstLastName {
            get {
                return ResourceManager.GetString("FirstLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @FirstName.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Fullname.
        /// </summary>
        internal static string Fullname {
            get {
                return ResourceManager.GetString("Fullname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Gender.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Group.
        /// </summary>
        internal static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @GroupId.
        /// </summary>
        internal static string GroupId {
            get {
                return ResourceManager.GetString("GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Icon.
        /// </summary>
        internal static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Id.
        /// </summary>
        internal static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Identification.
        /// </summary>
        internal static string Identification {
            get {
                return ResourceManager.GetString("Identification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdentificationType.
        /// </summary>
        internal static string IdentificationType {
            get {
                return ResourceManager.GetString("IdentificationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdFather.
        /// </summary>
        internal static string IdFather {
            get {
                return ResourceManager.GetString("IdFather", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdOption.
        /// </summary>
        internal static string IdOption {
            get {
                return ResourceManager.GetString("IdOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdPermission.
        /// </summary>
        internal static string IdPermission {
            get {
                return ResourceManager.GetString("IdPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdPerson.
        /// </summary>
        internal static string IdPerson {
            get {
                return ResourceManager.GetString("IdPerson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdProfile.
        /// </summary>
        internal static string IdProfile {
            get {
                return ResourceManager.GetString("IdProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdRoll.
        /// </summary>
        internal static string IdRoll {
            get {
                return ResourceManager.GetString("IdRoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IdUserType.
        /// </summary>
        internal static string IdUserType {
            get {
                return ResourceManager.GetString("IdUserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ImageLogo.
        /// </summary>
        internal static string ImageLogo {
            get {
                return ResourceManager.GetString("ImageLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IsActive.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IsLockedOut.
        /// </summary>
        internal static string IsLockedOut {
            get {
                return ResourceManager.GetString("IsLockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @IsSuperAdmin.
        /// </summary>
        internal static string IsSuperAdmin {
            get {
                return ResourceManager.GetString("IsSuperAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Key.
        /// </summary>
        internal static string Key {
            get {
                return ResourceManager.GetString("Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @LastName.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ModificationDate.
        /// </summary>
        internal static string ModificationDate {
            get {
                return ResourceManager.GetString("ModificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @OrderMenu.
        /// </summary>
        internal static string OrderMenu {
            get {
                return ResourceManager.GetString("OrderMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ParentId.
        /// </summary>
        internal static string ParentId {
            get {
                return ResourceManager.GetString("ParentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ProfileCode.
        /// </summary>
        internal static string ProfileCode {
            get {
                return ResourceManager.GetString("ProfileCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ProfileId.
        /// </summary>
        internal static string ProfileId {
            get {
                return ResourceManager.GetString("ProfileId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Prosition.
        /// </summary>
        internal static string Prosition {
            get {
                return ResourceManager.GetString("Prosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @RollCode.
        /// </summary>
        internal static string RollCode {
            get {
                return ResourceManager.GetString("RollCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @SecondLastName.
        /// </summary>
        internal static string SecondLastName {
            get {
                return ResourceManager.GetString("SecondLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @SeconfName.
        /// </summary>
        internal static string SeconfName {
            get {
                return ResourceManager.GetString("SeconfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @State.
        /// </summary>
        internal static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parametro.
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Synchronized.
        /// </summary>
        internal static string Synchronized {
            get {
                return ResourceManager.GetString("Synchronized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @TimeStamp.
        /// </summary>
        internal static string TimeStamp {
            get {
                return ResourceManager.GetString("TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Token.
        /// </summary>
        internal static string Token {
            get {
                return ResourceManager.GetString("Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Url.
        /// </summary>
        internal static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @UserCode.
        /// </summary>
        internal static string UserCode {
            get {
                return ResourceManager.GetString("UserCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Username.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @UserTypeId.
        /// </summary>
        internal static string UserTypeId {
            get {
                return ResourceManager.GetString("UserTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @Value.
        /// </summary>
        internal static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a @ViewForm.
        /// </summary>
        internal static string ViewForm {
            get {
                return ResourceManager.GetString("ViewForm", resourceCulture);
            }
        }
    }
}
